### ISSUE TITLE
libqalculate14 conflict with libqalculate6 when upgrading.

### ISSUE THREAD

**Issue by drkpkg** [Nitrux/nomad-desktop#13]
Hey guys, today I decide to upgrade my system, the problem begins when I try to make an **apt upgrade**

The following broken packages are displayed in the terminal.

![screenshot_20180928_002817](https://user-images.githubusercontent.com/972555/46188237-f4feab80-c2b5-11e8-9013-ef58444e3ad9.png)

Before the update package list the system didn't notify me about broken dependencies.

**Comment by UriHerrera** [comment]
Do not use `apt upgrade` use `apt dist-upgrade` instead when performing upgrades.

**Comment by UriHerrera** [comment]
Hi there!.

Please use the correct repository when adding a new issue. [Bug Repository for Nitrux 1.0.x Releases](https://github.com/Nitrux/nitrux-iso-bug-tracker).

Do not use `apt upgrade` use `apt dist-upgrade` instead when performing upgrades with APT using Konsole. We include the Software Updater KCM to perform upgrades using a GUI.

**Comment by drkpkg** [comment]
Sorry, next time gonna search better for issues :P 

Upgrading the system, thanks!
