### ISSUE TITLE
latte-dock and the top left nitrux menu icon vanished

### ISSUE THREAD

**Issue by pon-r** [Nitrux/nomad-desktop#14]
Hello;
today after update the most top-left (nitrux)menu icon and the whole dock menu bar at the bottom was gone.
running latte-dock says the process is already running and to use --replace. but all of that didn't help.
plz help.
https://my.mixtape.moe/nwtseo.png

**Comment by UriHerrera** [comment]
Hi there,

How did you upgrade?.

**Comment by UriHerrera** [comment]
Hi there, Please use the correct repository to create issues. [Bug Repository for Nitrux 1.0.x Releases](https://github.com/Nitrux/nitrux-iso-bug-tracker)
