### ISSUE TITLE
Add script to update /etc/apt/sources.list

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nomad-desktop#4]
Add a script as a package that updates the repository list to the next available Ubuntu release. For example:

````
deb http://archive.ubuntu.com/ubuntu artful main restricted universe multiverse
````

To

````
deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
````

Or provide our own package that overrides the default `/etc/apt/sources.list `.

**Comment by luis-lavaire** [comment]
`sed -i 's/$OLD_RELEASE_CODENAME/$NEW_RELEASE_CODENAME/g' /etc/apt/sources.list` can do the work. Is this what you want?

**Comment by UriHerrera** [comment]
Yes, pretty much,

**Comment by luis-lavaire** [comment]
Where does it need to be placed?

**Comment by UriHerrera** [comment]
`/etc/apt/sources.list` is the path.

**Comment by luis-lavaire** [comment]
No, no, @UriHerrera, I mean the script.

**Comment by UriHerrera** [comment]
Ah, in `/usr/local/bin` or `/opt`.
